'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class DatabaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DatabaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Books() As DbSet(Of Book)
    Public Property Rents() As DbSet(Of Rent)
    Public Property Tables() As DbSet(Of Table)
    Public Property UserDBs() As DbSet(Of UserDB)

    Public Overridable Function InsertDataIntoUserTable(userID As String, user_first_name As String, second_name As String) As Integer
        Dim userIDParameter As ObjectParameter = If(userID IsNot Nothing, New ObjectParameter("UserID", userID), New ObjectParameter("UserID", GetType(String)))

        Dim user_first_nameParameter As ObjectParameter = If(user_first_name IsNot Nothing, New ObjectParameter("User_first_name", user_first_name), New ObjectParameter("User_first_name", GetType(String)))

        Dim second_nameParameter As ObjectParameter = If(second_name IsNot Nothing, New ObjectParameter("Second_name", second_name), New ObjectParameter("Second_name", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertDataIntoUserTable", userIDParameter, user_first_nameParameter, second_nameParameter)
    End Function

    Public Overridable Function RentedMacbeth() As ObjectResult(Of String)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("RentedMacbeth")
    End Function

    Public Overridable Function TotalBooks() As ObjectResult(Of TotalBooks_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of TotalBooks_Result)("TotalBooks")
    End Function

End Class
