'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Book
    Public Property BookID As Integer
    Public Property BookName As String
    Public Property AuthorName As String
    Public Property Copies As Short
    Public Property In_Stock As Boolean
    Public Property Discription As String

    Public Overridable Property Rents As ICollection(Of Rent) = New HashSet(Of Rent)

End Class
Partial Public Class Rent
    Public Property Rental_ID As Integer
    Public Property UserID As Integer
    Public Property BookID As Integer

    Public Overridable Property Book As Book
    Public Overridable Property UserDBs As ICollection(Of UserDB) = New HashSet(Of UserDB)

End Class
Partial Public Class Table
    Public Property BookID As Integer
    Public Property BookName As Integer
    Public Property AuthorName As String
    Public Property Copies As Decimal
    Public Property Avialable As Boolean
    Public Property Discription As String

End Class
Partial Public Class UserDB
    Public Property UserID As String
    Public Property User_first_name As String
    Public Property Second_name As String
    Public Property Active As Boolean
    Public Property Books_Rented_ As String
    Public Property Address As String
    Public Property email As String
    Public Property Password As String

    Public Overridable Property Rent As Rent

End Class
Partial Public Class TotalBooks_Result
    Public Property AuthorName As String
    Public Property BookName As String

End Class
