'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Book
    Public Property BookID As Integer
    Public Property BookName As String
    Public Property AuthorName As String
    Public Property Copies As Short
    Public Property In_Stock As Boolean
    Public Property Discription As String
    Public Property Genre As String

    Public Overridable Property Rents As ICollection(Of Rent) = New HashSet(Of Rent)
    Public Overridable Property User_Comment As ICollection(Of User_Comment) = New HashSet(Of User_Comment)

End Class
Partial Public Class Rent
    Public Property Rental_ID As Integer
    Public Property UserID As String
    Public Property BookID As Integer
    Public Property CollectionDate As Date
    Public Property CollectionTime As System.TimeSpan

    Public Overridable Property Book As Book
    Public Overridable Property UserDB As UserDB

End Class
Partial Public Class User_Comment
    Public Property UserID As String
    Public Property Book As String
    Public Property BookID As Nullable(Of Integer)
    Public Property Comment As String
    Public Property Review As Boolean

    Public Overridable Property Book1 As Book
    Public Overridable Property UserDB As UserDB

End Class
Partial Public Class UserDB
    Public Property UserID As String
    Public Property User_first_name As String
    Public Property Second_name As String
    Public Property Active As Boolean
    Public Property Books_Rented_ As String
    Public Property Address As String
    Public Property email As String
    Public Property Password As String

    Public Overridable Property Rents As ICollection(Of Rent) = New HashSet(Of Rent)
    Public Overridable Property User_Comment As User_Comment

End Class
